### ISSUE TITLE
`README` needs to be updated

### ISSUE THREAD

**Issue by Rubix982** [mehrankamal/clox#16]
# Description

Hi, @mehrankamal. I wanted to setup this project locally. Please add description about the features of the project and the setup steps.

Thank you.

# Benefit

Will be quicker to setup and easier to debug possible issues.

**Comment by mehrankamal** [comment]
Hi @Rubix982, thank you for bringing this up! I've added detailed instructions for setting up the compiler locally. Let me know if you need any further assistance or run into any issues—happy to help! :)

**Comment by Rubix982** [comment]
Thanks, @mehrankamal.
